FROM ubuntu:focal

LABEL maintainer "VCityTeam"
LABEL source.repo "https://github.com/VCityTeam/UD-Demo-vcity-geovolume-docker.git"

RUN apt-get update

# The container will serve (through http) the client code 

######### Install the UD-Viz demo per se (client code) and build it
# Node version 14 is required. For its installation (on focal) refer to e.g.
#  https://computingforgeeks.com/install-node-js-14-on-ubuntu-debian-linux/
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs
RUN node --version
RUN npm --version
RUN npm install -g npm@latest
RUN apt-get install -y git
RUN git --version

######### Install UD-Demo-vcity-geovolume

WORKDIR /
RUN git clone --recurse-submodules https://github.com/VCityTeam/UD-Demo-vcity-geovolume.git
WORKDIR /UD-Demo-vcity-geovolume
RUN npm install
RUN npm run build

WORKDIR /
RUN git clone https://github.com/VCityTeam/UD-SimpleServer.git
WORKDIR /UD-SimpleServer
RUN npm install

EXPOSE 8080
CMD [ "node", "./index.js", "/UD-Demo-vcity-geovolume","8080"]
