version: '3.4'
services:
  geovolume_server:
    build:
      context: ./geovolumeServer-context
    hostname: geovolumeServer
    ports:
      - "${GEOVOLUME_SERVER_PORT}:3000"
  ud_viz_demo:
    build:
      context: ./demo-context
    hostname: geovolumeDemo
    ports:
      - "${UD_VIZ_DEMO_PORT}:8000"